const images = {
    ATL: require('./ATL.png'),
    BKN: require('./BKN.png'),
    BOS: require('./BOS.png'),
    CHA: require('./CHA.png'),
    CLE: require('./CLE.png'),
    DAL: require('./DAL.png'),
    DEN: require('./DEN.png'),
    DET: require('./DET.png'),
    GS: require('./GS.png'),
    HOU: require('./HOU.png'),
    LAC: require('./LAC.png'),
    LAL: require('./LAL.png'),
    MEM: require('./MEM.png'),
    MIA: require('./MIA.png'),
    MIL: require('./MIL.png'),
    MIN: require('./MIN.png'),
    NO: require('./NO.png'),
    NY: require('./NY.png'),
    OKC: require('./OKC.png'),
    ORL: require('./ORL.png'),
    PHI: require('./PHI.png'),
    PHX: require('./PHX.png'),
    POR: require('./POR.png'),
    SA: require('./SA.png'),
    SAC: require('./SAC.png'),
    TOR: require('./TOR.png'),
    UTA: require('./UTA.png'),
    WAS: require('./WAS.png')
}

export default images;