const images = {
    ATL: require('./ATL.png'),
    BRO: require('./BRO.png'),
    BOS: require('./BOS.png'),
    CHA: require('./CHA.png'),
    CHI: require('./CHI.png'),
    CLE: require('./CLE.png'),
    DAL: require('./DAL.png'),
    DEN: require('./DEN.png'),
    DET: require('./DET.png'),
    GSW: require('./GSW.png'),
    HOU: require('./HOU.png'),
    IND: require('./IND.png'),
    LAC: require('./LAC.png'),
    LAL: require('./LAL.png'),
    MEM: require('./MEM.png'),
    MIA: require('./MIA.png'),
    MIL: require('./MIL.png'),
    MIN: require('./MIN.png'),
    NOP: require('./NOP.png'),
    NYK: require('./NYK.png'),
    OKC: require('./OKC.png'),
    ORL: require('./ORL.png'),
    PHI: require('./PHI.png'),
    PHX: require('./PHX.png'),
    POR: require('./POR.png'),
    SAS: require('./SAS.png'),
    SAC: require('./SAC.png'),
    TOR: require('./TOR.png'),
    UTA: require('./UTA.png'),
    WAS: require('./WAS.png')
}

export default images;